version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost/api
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db: 
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/project_dashboard
      - SECRET_KEY=your-super-secret-key-change-in-production
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=project_dashboard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_db_user"]
      interval: 5s
      timeout: 5s
      retries: 5  

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 